global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['todo-prometheus:9090']
  - job_name: 'todo-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['todo-app:5555']
  - job_name: 'grafana'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['todo-grafana:3000']
  - job_name: 'todo-db'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['todo-db-exporter:9187']
  - job_name: 'todo-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['todo-app:8888']