{
 "title": "RED Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": "label_values(service)" },
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   { "name": "path", "label": "Endpoint", "query": "label_values(http_path)" }
  ]
 },
 "panels": [
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "In total Req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_in_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) "
    }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "singlestat",
   "description": "Incoming HTTP Requests per second for the selected endpoints and applications",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))"
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "singlestat",
   "description": "The error rate of incoming http requests for the selected endpoints and applications",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0"
    }
   ]
  },
  {
   "title": "Out total Req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_out_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) "
    }
   ]
  },
  {
   "title": "Out Req / Sec",
   "type": "singlestat",
   "description": "Outgoing HTTP Requests per second issued towards the selected endpoints from the given application",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Out Error Rate",
   "type": "singlestat",
   "description": "The error rate of outgoing http requests issued towards the selected endpoints of the selected application",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0"
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0"
    },
    {
     "expr": "sum(increase(http_in_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.25, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.5, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.75, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.9, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.99, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path)) >= 0\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0) * 0"
    }
   ]
  },
  {
   "title": "In Req vs Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_in_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_method)",
     "legendFormat": "{{http_method}}"
    },
    {
     "expr": "sum(irate(http_in_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\", http_status=~\"5..\"}[$__range]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Out Req vs Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_out_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_method)",
     "legendFormat": "{{http_method}}"
    },
    {
     "expr": "sum(irate(http_out_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\", http_status=~\"5..\"}[$__range]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "In Histogram of Quantiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_in_bucket{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Out Histogram of Quantiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_out_bucket{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Outgoing Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(label_join(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "label_join(sum(increase(http_out_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) \n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) > 0, \"http_url\", \"\", \"http_host\", \"http_path\")"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.25, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.5, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.75, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.9, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.99, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "label_join((sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path)) >= 0\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) > 0) * 0 , \"http_url\", \"\", \"http_host\", \"http_path\")"
    }
   ]
  },
  {
   "title": "In Quantiles of Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (le))",
     "legendFormat": "99th Quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Out Quantiles of Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (le))",
     "legendFormat": "99th Quantile"
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "In total Req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_in_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) "
    }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "singlestat",
   "description": "Incoming HTTP Requests per second for the selected endpoints and applications",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))"
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "singlestat",
   "description": "The error rate of incoming http requests for the selected endpoints and applications",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 24 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0"
    }
   ]
  },
  {
   "title": "Out total Req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_out_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) "
    }
   ]
  },
  {
   "title": "Out Req / Sec",
   "type": "singlestat",
   "description": "Outgoing HTTP Requests per second issued towards the selected endpoints from the given application",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Out Error Rate",
   "type": "singlestat",
   "description": "The error rate of outgoing http requests issued towards the selected endpoints of the selected application",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 24 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0"
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0"
    },
    {
     "expr": "sum(increase(http_in_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.25, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.5, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.75, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.9, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.99, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path)) >= 0\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0) * 0"
    }
   ]
  },
  {
   "title": "In Req vs Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_in_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_method)",
     "legendFormat": "{{http_method}}"
    },
    {
     "expr": "sum(irate(http_in_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\", http_status=~\"5..\"}[$__range]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Out Req vs Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_out_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_method)",
     "legendFormat": "{{http_method}}"
    },
    {
     "expr": "sum(irate(http_out_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\", http_status=~\"5..\"}[$__range]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "In Histogram of Quantiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_in_bucket{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Out Histogram of Quantiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_out_bucket{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Outgoing Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(label_join(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "label_join(sum(increase(http_out_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) \n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) > 0, \"http_url\", \"\", \"http_host\", \"http_path\")"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.25, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.5, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.75, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.9, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.99, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "label_join((sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path)) >= 0\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) > 0) * 0 , \"http_url\", \"\", \"http_host\", \"http_path\")"
    }
   ]
  },
  {
   "title": "In Quantiles of Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (le))",
     "legendFormat": "99th Quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Out Quantiles of Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (le))",
     "legendFormat": "99th Quantile"
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "In total Req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 47 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_in_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) "
    }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "singlestat",
   "description": "Incoming HTTP Requests per second for the selected endpoints and applications",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))"
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "singlestat",
   "description": "The error rate of incoming http requests for the selected endpoints and applications",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 47 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0"
    }
   ]
  },
  {
   "title": "Out total Req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 47 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_out_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) "
    }
   ]
  },
  {
   "title": "Out Req / Sec",
   "type": "singlestat",
   "description": "Outgoing HTTP Requests per second issued towards the selected endpoints from the given application",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Out Error Rate",
   "type": "singlestat",
   "description": "The error rate of outgoing http requests issued towards the selected endpoints of the selected application",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 47 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0"
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0"
    },
    {
     "expr": "sum(increase(http_in_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.25, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.5, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.75, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.9, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.99, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path)) >= 0\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0) * 0"
    }
   ]
  },
  {
   "title": "In Req vs Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_in_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_method)",
     "legendFormat": "{{http_method}}"
    },
    {
     "expr": "sum(irate(http_in_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\", http_status=~\"5..\"}[$__range]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Out Req vs Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_out_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_method)",
     "legendFormat": "{{http_method}}"
    },
    {
     "expr": "sum(irate(http_out_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\", http_status=~\"5..\"}[$__range]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "In Histogram of Quantiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_in_bucket{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Out Histogram of Quantiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_out_bucket{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Outgoing Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(label_join(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "label_join(sum(increase(http_out_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) \n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) > 0, \"http_url\", \"\", \"http_host\", \"http_path\")"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.25, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.5, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.75, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.9, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.99, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "label_join((sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path)) >= 0\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) > 0) * 0 , \"http_url\", \"\", \"http_host\", \"http_path\")"
    }
   ]
  },
  {
   "title": "In Quantiles of Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (le))",
     "legendFormat": "99th Quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Out Quantiles of Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (le))",
     "legendFormat": "99th Quantile"
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "In total Req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 70 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_in_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) "
    }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "singlestat",
   "description": "Incoming HTTP Requests per second for the selected endpoints and applications",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 70 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))"
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "singlestat",
   "description": "The error rate of incoming http requests for the selected endpoints and applications",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 70 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0"
    }
   ]
  },
  {
   "title": "Out total Req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 70 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_out_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) "
    }
   ]
  },
  {
   "title": "Out Req / Sec",
   "type": "singlestat",
   "description": "Outgoing HTTP Requests per second issued towards the selected endpoints from the given application",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 70 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Out Error Rate",
   "type": "singlestat",
   "description": "The error rate of outgoing http requests issued towards the selected endpoints of the selected application",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 70 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0"
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0"
    },
    {
     "expr": "sum(increase(http_in_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.25, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.5, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.75, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.9, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.99, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path)) >= 0\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0) * 0"
    }
   ]
  },
  {
   "title": "In Req vs Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_in_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_method)",
     "legendFormat": "{{http_method}}"
    },
    {
     "expr": "sum(irate(http_in_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\", http_status=~\"5..\"}[$__range]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Out Req vs Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_out_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_method)",
     "legendFormat": "{{http_method}}"
    },
    {
     "expr": "sum(irate(http_out_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\", http_status=~\"5..\"}[$__range]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "In Histogram of Quantiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_in_bucket{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Out Histogram of Quantiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_out_bucket{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Outgoing Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "sum(label_join(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "label_join(sum(increase(http_out_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) \n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) > 0, \"http_url\", \"\", \"http_host\", \"http_path\")"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.25, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.5, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.75, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.9, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.99, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "label_join((sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path)) >= 0\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) > 0) * 0 , \"http_url\", \"\", \"http_host\", \"http_path\")"
    }
   ]
  },
  {
   "title": "In Quantiles of Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (le))",
     "legendFormat": "99th Quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Out Quantiles of Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (le))",
     "legendFormat": "99th Quantile"
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "In total Req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 93 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_in_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) "
    }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "singlestat",
   "description": "Incoming HTTP Requests per second for the selected endpoints and applications",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 93 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))"
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "singlestat",
   "description": "The error rate of incoming http requests for the selected endpoints and applications",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 93 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0"
    }
   ]
  },
  {
   "title": "Out total Req",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 93 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_out_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) "
    }
   ]
  },
  {
   "title": "Out Req / Sec",
   "type": "singlestat",
   "description": "Outgoing HTTP Requests per second issued towards the selected endpoints from the given application",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 93 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Out Error Rate",
   "type": "singlestat",
   "description": "The error rate of outgoing http requests issued towards the selected endpoints of the selected application",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 93 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0"
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0"
    },
    {
     "expr": "sum(increase(http_in_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.25, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.5, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.75, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.9, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "sum(histogram_quantile(0.99, rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))) by (http_path)  > 0"
    },
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path)) >= 0\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) > 0) * 0"
    }
   ]
  },
  {
   "title": "In Req vs Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_in_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_method)",
     "legendFormat": "{{http_method}}"
    },
    {
     "expr": "sum(irate(http_in_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\", http_status=~\"5..\"}[$__range]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Out Req vs Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_out_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_method)",
     "legendFormat": "{{http_method}}"
    },
    {
     "expr": "sum(irate(http_out_count{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\", http_status=~\"5..\"}[$__range]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "In Histogram of Quantiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_in_bucket{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Out Histogram of Quantiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_out_bucket{service=\"api-gateway\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Outgoing Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "sum(label_join(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "label_join(sum(increase(http_out_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) \n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) > 0, \"http_url\", \"\", \"http_host\", \"http_path\")"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.25, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.5, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.75, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.9, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "sum(label_join(histogram_quantile(0.99, rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0"
    },
    {
     "expr": "label_join((sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_path) \n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path)) >= 0\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (http_host,http_path) > 0) * 0 , \"http_url\", \"\", \"http_host\", \"http_path\")"
    }
   ]
  },
  {
   "title": "In Quantiles of Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (le))",
     "legendFormat": "99th Quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_in_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Out Quantiles of Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_out_bucket{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) by (le))",
     "legendFormat": "99th Quantile"
    }
   ]
  }
 ]
}